[package]
name = "shrs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MrPicklePinosaur"]
description = "modular library to build your own shell in rust"
repository = "https://github.com/MrPicklePinosaur/sh.rs"

[features]

[dependencies]
pest = "2"
pest_derive = "2"

thiserror = "1"